jobs:
  - name: csv
    conf:
      spark.cassandra.connection.host: devcass8.yagnaiq.in
      spark.cassandra.auth.username: nilesh
      spark.cassandra.auth.password: Yagna123

    metadata:
      cql.keyspace: kb_us
      env.profile: NA
      
    extract:
      - format: com.databricks.spark.csv
        options:
          path: s3a://dry-repo/media/Repo/data.csv
          header: true

    load:
      - format: console
