jobs:
  - name: VMware Lead Aggregator

    extract:
      - format: org.apache.spark.sql.kafka010.KafkaSourceProvider
        options:
          kafka.bootstrap.servers: g-aws-dev.yagnaiq.com:9092
          subscribe: vmware-product-aggregated

    transform:

      - add:
          col: convertedCurrency
          ref: QuoteHeader.Currency

      - add:
          col: currency
          ref: QuoteHeader.Currency

      - add:
          col: quoteId
          ref: QuoteHeader.QuoteNumber

      - add:
          col: quoteName
          ref: Quote.quoteName

      - add:
          col: digitalContent
          ref: Quote.digitalContentList

      - add:
          col: quoteUuid
          value: null

      - add:
          col: quoteLink
          value: null

      - add:
          col: yagnaQuoteId
          value: null

      - add:
          col: yagnaNewQuoteId
          value: null

      - add:
          col: quoteType
          value: RENEWAL

      - add:
          col: leadProductsUUIDs
          udf:
            function: stringToSeq
            params:
              - ""
              - ""

      - add:
          col: quoteExpiration
          ref: QuoteHeader.QuoteExpiration

      - add:
          col: quoteVersion
          ref: QuoteHeader.QuoteVersion

      - add:
          col: quoteVersion
          ref: QuoteHeader.QuoteVersion

      - add:
          col: quoteModifier
          udf:
            function: split
            col:
              - QuoteHeader.QuoteNumber
            params:
              - "-"
              - 1

      - add:
          col: quoteCreationDate
          ref: QuoteHeader.QuoteDate

      - struct:
          col:
            - convertedCurrency
            - currency
            - digitalContentList
            - InstallBase.leadProducts
            - leadProductsUUIDs
            - pricingSummary()
            - quoteCreationDate
            - quoteExpiration
            - quoteId
            - quoteLink
            - quoteModifier
            - quoteName
            - quoteType
            - quoteUuid
            - quoteVersion
            - yagnaNewQuoteId
            - yagnaQuoteId
          target: leadQuote

      - group:
          col:
            - ExtractedQuoteNumber
          agg:
            - col:
                - InstallBase.trackerTransactionIds
              agg: first
            - col:
                - QuoteHeader.TotalDiscount
              agg: sum
              target: TotalDiscount
            - col:
                - QuoteHeader
              agg: collect_list
            - col:
                - Quote
              agg: collect_list
            - col:
                - InstallBase
              agg: collect_list
            - col:
                - leadQuote
              agg: collect_list
              target: leadQuotes
            - col:
                - InstallBaseFirst
              agg: first
            - col:
                - rawLead
              agg: collect_list

      - struct:
          col:
            - QuoteHeader
            - Quote
            - InstallBase
          target: Quote

      - struct:
          col:
            - QuoteHeader
            - Quote
            - InstallBase
          target: Quote

      - rename:
          col: InstallBaseFirst
          to: InstallBase

      - add:
          col: rawLead
          udf:
            function: colToJson
            col:
              - rawLead

      - struct:
          col:
            - ExtractedQuoteNumber
            - InstallBase.trackerTransactionIds
            - TotalDiscount
            - Quote
            - leadQuotes
            - InstallBase
            - rawLead
          target: Lead

    load:
      - format: org.apache.spark.sql.kafka010.KafkaSourceProvider
        options:
          kafka.bootstrap.servers: g-aws-dev.yagnaiq.com:9092
          topic: vmware-lead-aggregated
